plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'net.hobbyshot.sagasofyggdrasil'
    compileSdk 36

    defaultConfig {
        applicationId "net.hobbyshot.sagasofyggdrasil"
        minSdk 24
        targetSdk 36
        versionCode 2
        versionName "1.0.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (keystoreProperties.size() > 0) {
                storeFile = file(keystoreProperties['storeFile'])
                storePassword = keystoreProperties['storePassword']
                keyAlias = keystoreProperties['keyAlias']
                keyPassword = keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            if (keystoreProperties.size() > 0) {
                signingConfig signingConfigs.release
            }
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "sagas-of-yggdrasil-${variant.name}.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

tasks.configureEach { task ->
    if (task.name == "bundleRelease") {
        task.doLast {
            def oldFile = file("${layout.buildDirectory.get().asFile}/outputs/bundle/release/app-release.aab")
            if (oldFile.exists()) {
                def newFile = file("${layout.buildDirectory.get().asFile}/outputs/bundle/release/sagas-of-yggdrasil-release.aab")
                if (newFile.exists()) newFile.delete()
                oldFile.renameTo(newFile)
            }
        }
    } else if (task.name == "bundleDebug") {
        task.doLast {
            def oldFile = file("${layout.buildDirectory.get().asFile}/outputs/bundle/debug/app-debug.aab")
            if (oldFile.exists()) {
                def newFile = file("${layout.buildDirectory.get().asFile}/outputs/bundle/debug/sagas-of-yggdrasil-debug.aab")
                if (newFile.exists()) newFile.delete()
                oldFile.renameTo(newFile)
            }
        }
    }
}
